import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'

// export const metadata = {
//   title: "248 Labs",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon_io/favicon.ico" type="image/png" sizes="32x32" />
        <title>248 Labs</title>
        <meta name="title" content="Changing the way games are madete" />
        <meta name="description" content="Redefining the future of play" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://metatags.io/" />
        <meta property="og:title" content="Changing the way games are madete" />
        <meta property="og:description" content="Redefining the future of play" />
        <meta property="og:image" content="https://i.postimg.cc/dQNHfqjH/capture-20240318122231008.png" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://metatags.io/" />
        <meta property="twitter:title" content="Changing the way games are madete" />
        <meta property="twitter:description" content="Redefining the future of play" />
        <meta property="twitter:image" content="https://i.postimg.cc/dQNHfqjH/capture-20240318122231008.png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
